### ISSUE TITLE
Package is not pre-transpiled

### ISSUE THREAD

**Issue by mukunku** [JavadRasouli/ng2-permission#1]
When you add the package to your project using npm there are no .js files. And it's quite difficult to get this specific node_module to transpile along with the rest of your project.

**Comment by JavadRasouli** [comment]
i assume that you use typescript and angular-cli. .js files will be added as soon as possible.

**Comment by JavadRasouli** [comment]
Now you can use ng2-permission.js from `dist` directory.

**Comment by mukunku** [comment]
Thank you. I'm using SystemJS and Angular CLI as seen in the Quick Demo at www.Angular.io
