### ISSUE TITLE
issue on using it

### ISSUE THREAD

**Issue by sheriatash** [JavadRasouli/ng2-permission#13]
hi @JavadRasouli , 
I am new to angular and I have a problem using this module, 
I have angular inside my .net project API, I did:
npm install angular2-permission --save
however as soon as I use it in appmodule 
I have errors and my build fails. 

would you please help me how I can use it?

**Comment by JavadRasouli** [comment]
hi. First, for a long time I have not been working on this project, to solve your problem I recommend you following Library that is so similar to this one and also more better.
[https://github.com/AlexKhymenko/ngx-permissions#readme](ngx-permissions)
