### ISSUE TITLE
Multiple instances of PermissionService 

### ISSUE THREAD

**Issue by mcherb** [JavadRasouli/ng2-permission#5]
Hi,

In my AppModule i have imported Ng2Permission, then i have defined the permissions of my app. Good so far.
In an other module (lazy loaded) i use the template directive's, so i have to import Ng2Permission in this module again. The issue is Angular creates a new instance of PermisionService for me. i want to configure the permissions once.

Could you see please (might be add forRoot method to be used in AppModule only)

**Comment by jmparraguez-haulmer** [comment]
Here is a fork with forRoot implemented
https://github.com/mastropinguino/ng2-permission
